export enum ConfigKeys {
  DATABASE_URL = "DATABASE_URL",
  FRONTEND_URL = "FRONTEND_URL",
  JWT_SECRET = "JWT_SECRET",
  FIRST_CONTROLLER_USERNAME = "FIRST_CONTROLLER_USERNAME",
  FIRST_CONTROLLER_PASSWORD = "FIRST_CONTROLLER_PASSWORD",
  FIRST_CONTROLLER_FIRSTNAME = "FIRST_CONTROLLER_FIRSTNAME",
  FIRST_CONTROLLER_LASTNAME = "FIRST_CONTROLLER_LASTNAME",
}
