export enum ConfigKeys {
  DATABASE_URL = "DATABASE_URL",
  FRONTEND_URL = "FRONTEND_URL",
  JWT_SECRET = "JWT_SECRET",
  INITIAL_CONTROLLER_USERNAME = "INITIAL_CONTROLLER_USERNAME",
  INITIAL_CONTROLLER_PASSWORD = "INITIAL_CONTROLLER_PASSWORD",
}
