name: Build and Release Windows EXE

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyyaml

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed dpt-boot-manager.py

      - name: Copy docker-compose file
        run: |
          copy docker-compose.prod.yml dist\docker-compose.prod.yml

      - name: Upload EXE as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: DockerGUI-1.0.${{ github.run_number }}
          path: dist/*
          compression-level: 0
          retention-days: 30

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: dist/*
