name: Build and Release Windows EXE

on:
  push:
    branches:
      - main
    paths:
      - "packages/boot-manager/dpt-boot-manager.py"
      - "docker/docker-compose.prod.yml"
      - "packages/boot-manager/requirements.txt"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r packages/boot-manager/requirements.txt

      - name: Update version in code
        shell: bash
        run: |
          sed -i "s/^CURRENT_VERSION = .*/CURRENT_VERSION = \"v1.0.${{ github.run_number }}\"/g" packages/boot-manager/dpt-boot-manager.py

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed packages/boot-manager/dpt-boot-manager.py --name "BootManagerDPT_v1.0.${{ github.run_number }}"

      - name: Copy docker-compose file
        run: |
          copy docker/docker-compose.prod.yml dist\docker-compose-v1.0.${{ github.run_number }}.yml

      - name: Upload EXE as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: BootManagerDPT_v1.0.${{ github.run_number }}
          path: dist/*
          compression-level: 0
          retention-days: 30

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: dist/*
