name: Build and Release Windows EXE

on:
  push:
    branches:
      - docker
    paths:
      - "dpt-boot-manager.py"
      - "docker-compose.prod.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyyaml

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed dpt-boot-manager.py.py

      - name: Copy docker-compose file
        run: |
          copy docker-compose.prod.yml dist\docker-compose.prod.yml

      - name: Create version number
        id: version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: DockerGUI-${{ env.VERSION }}
          path: dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: dist/*
