name: Docker

on:
  push:
    branches:
      - docker

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api_changed }}
      web_changed: ${{ steps.filter.outputs.web_changed }}
      db_changed: ${{ steps.filter.outputs.db_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            # Adjust these filters as you see fit
            api_changed:
              - '**'
            web_changed:
              - '**'
            db_changed:
              - '**'

  build_and_push_db_image:
    name: Build and Push DB Image
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.db_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push DB Image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/database
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:db-latest

  build_and_push_api_image:
    name: Build and Push API Image
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.api_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:api-latest

  build_and_push_web_image:
    name: Build and Push Web Image
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.web_changed == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Web Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: web
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:web-latest
