name: Docker

on:
  push:
    branches:
      - docker

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api_changed }}
      web_changed: ${{ steps.filter.outputs.web_changed }}
      db_changed: ${{ steps.filter.outputs.db_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api_changed:
              - '**'
            web_changed:
              - '**'
            db_changed:
              - 'packages/database/**'

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: paths-filter
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------------------------------
      # 1) Build + Push DB Image (if changed)
      # ---------------------------------------
      - name: Build and Push DB Image
        if: ${{ needs.paths-filter.outputs.db_changed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          # The Dockerfile for DB is assumed in packages/database/
          context: ./packages/database
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:db-latest

      # ---------------------------------------
      # 2) Build + Push API Image (if changed)
      # ---------------------------------------
      - name: Build and Push API Image
        if: ${{ needs.paths-filter.outputs.api_changed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          # Use root Dockerfile
          context: .
          file: ./Dockerfile
          # Name of the multi-stage target
          target: api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:api-latest

      # ---------------------------------------
      # 3) Build + Push Web Image (if changed)
      # ---------------------------------------
      - name: Build and Push Web Image
        if: ${{ needs.paths-filter.outputs.web_changed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          # Use root Dockerfile
          context: .
          file: ./Dockerfile
          target: web
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dpt:web-latest
